### ISSUE TITLE
Crime Reports Sensor Implementation 

### ISSUE THREAD

**Issue by brianjking** [happyleavesaoc/my-home-automation#3]
@happyleavesaoc -- Does your `sensor.crimereports` actually work? I found [crimereports.yaml](https://github.com/happyleavesaoc/my-home-automation/blob/master/homeassistant/sensors/crimereports.yaml) in your repo, however, Home Assistant doesn't list this component anywhere.

Any info on how to get this implemented would be greatly appreciated.

Thanks!

**Comment by happyleavesaoc** [comment]
Yes, it works, but only on my local machine right now. My PR to HASS was rejected and I still need to address the requested changes.
