### ISSUE TITLE
Setting up brief/template

### ISSUE THREAD

**Issue by resnostyle** [happyleavesaoc/my-home-automation#4]
I've been looking at your repo using the templates, and I dont see how things flow.  I've tried emulating what you have and I get nothing out of the tts side.

**Comment by happyleavesaoc** [comment]
Is there a specific part that isn't working? Do you have a repo I could look at?

**Comment by resnostyle** [comment]
Yea, here's my repo: https://gitlab.com/resnostyle/homeautomation/tree/template_repair

Here's my template that I'm trying to use. https://gitlab.com/resnostyle/homeautomation/blob/template_repair/templates/brief.yaml
I'm attempting to call it here: https://gitlab.com/resnostyle/homeautomation/blob/template_repair/automation/chromecast.yaml

I cant get it to say the variable I'm trying to pass in, and the config validated.

**Comment by happyleavesaoc** [comment]
For `message:` in `chromecast.yaml`, set the value to `!include ../templates/brief.yaml`.

In `brief.yaml`, you aren't outputting anything. You'll have to actually call one of the macros. Try `{{morning_briefing_generic()}}`.

You can test the output of your brief by copying the whole thing into your UI's template editor (icon under "Developer tools" near the bottom of the left nav menu)

**Comment by resnostyle** [comment]
I see, now I've missed the conditionals. I overlooked them initially.  This also explains why I couldnt find where you were making the calls from the automation.

Thanks for your help
